// ===========================================
// MOCK DATA PARA INGRESOS
// ===========================================

import type {
  ReservaIngreso,
  VentaExtraReporte,
  IngresosStats,
  TendenciaMensual,
  MetodoPago,
} from './types'

// Helper para generar fechas
const hoy = new Date()
const formatDate = (d: Date) => d.toISOString().split('T')[0]
const addDays = (d: Date, days: number) => new Date(d.getTime() + days * 24 * 60 * 60 * 1000)

// ===========================================
// CANCHAS (referencia)
// ===========================================
const CANCHAS = [
  { id: 'c1', nombre: 'Cancha 1 - F5' },
  { id: 'c2', nombre: 'Cancha 2 - F5' },
  { id: 'c3', nombre: 'Cancha 3 - F7' },
]

// ===========================================
// RESERVAS CON DATOS DE INGRESO
// ===========================================
export const mockReservasIngreso: ReservaIngreso[] = [
  // Hoy
  {
    id: 'r-h1',
    canchaId: 'c1',
    canchaNombre: 'Cancha 1 - F5',
    fecha: formatDate(hoy),
    horaInicio: '06:00',
    horaFin: '07:00',
    duracionHoras: 1,
    precioTotal: 80,
    precioBase: 80,
    adelantoPagado: 80,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'efectivo',
    origen: 'manual',
    clienteNombre: 'Juan Pérez',
    createdAt: new Date(hoy.getTime() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-h2',
    canchaId: 'c2',
    canchaNombre: 'Cancha 2 - F5',
    fecha: formatDate(hoy),
    horaInicio: '07:00',
    horaFin: '08:00',
    duracionHoras: 1,
    precioTotal: 100,
    precioBase: 100,
    adelantoPagado: 30,
    saldoPendiente: 70,
    estadoPago: 'partial',
    metodoPago: 'culqi',
    origen: 'app',
    clienteNombre: 'María López',
    clienteTelefono: '999888777',
    createdAt: new Date(hoy.getTime() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-h3',
    canchaId: 'c3',
    canchaNombre: 'Cancha 3 - F7',
    fecha: formatDate(hoy),
    horaInicio: '18:00',
    horaFin: '19:00',
    duracionHoras: 1,
    precioTotal: 150,
    precioBase: 180,
    descuentoPromo: 30,
    promocionNombre: 'Noche de fútbol',
    adelantoPagado: 150,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'tarjeta_local',
    origen: 'manual',
    extrasTotal: 45,
    clienteNombre: 'Carlos García',
    createdAt: new Date(hoy.getTime() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-h4',
    canchaId: 'c1',
    canchaNombre: 'Cancha 1 - F5',
    fecha: formatDate(hoy),
    horaInicio: '19:00',
    horaFin: '21:00',
    duracionHoras: 2,
    precioTotal: 220,
    precioBase: 220,
    adelantoPagado: 220,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'yape',
    origen: 'manual',
    extrasTotal: 80,
    clienteNombre: 'Pedro Ramos',
    clienteTelefono: '998123456',
    createdAt: new Date(hoy.getTime() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-h5',
    canchaId: 'c2',
    canchaNombre: 'Cancha 2 - F5',
    fecha: formatDate(hoy),
    horaInicio: '20:00',
    horaFin: '21:00',
    duracionHoras: 1,
    precioTotal: 120,
    precioBase: 120,
    adelantoPagado: 0,
    saldoPendiente: 120,
    estadoPago: 'pending',
    metodoPago: 'efectivo',
    origen: 'manual',
    clienteNombre: 'Luis Mendoza',
    createdAt: new Date(hoy.getTime() - 30 * 60 * 1000).toISOString(),
  },

  // Días anteriores (última semana)
  {
    id: 'r-d1',
    canchaId: 'c1',
    canchaNombre: 'Cancha 1 - F5',
    fecha: formatDate(addDays(hoy, -1)),
    horaInicio: '15:00',
    horaFin: '16:00',
    duracionHoras: 1,
    precioTotal: 100,
    precioBase: 100,
    adelantoPagado: 100,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'efectivo',
    origen: 'manual',
    clienteNombre: 'Roberto Díaz',
    createdAt: new Date(addDays(hoy, -1).getTime() + 15 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d2',
    canchaId: 'c2',
    canchaNombre: 'Cancha 2 - F5',
    fecha: formatDate(addDays(hoy, -1)),
    horaInicio: '17:00',
    horaFin: '18:00',
    duracionHoras: 1,
    precioTotal: 120,
    precioBase: 120,
    adelantoPagado: 120,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'plin',
    origen: 'app',
    extrasTotal: 24,
    clienteNombre: 'Ana Torres',
    createdAt: new Date(addDays(hoy, -1).getTime() + 17 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d3',
    canchaId: 'c3',
    canchaNombre: 'Cancha 3 - F7',
    fecha: formatDate(addDays(hoy, -1)),
    horaInicio: '19:00',
    horaFin: '21:00',
    duracionHoras: 2,
    precioTotal: 320,
    precioBase: 320,
    adelantoPagado: 320,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'tarjeta_local',
    origen: 'manual',
    clienteNombre: 'Miguel Fernández',
    createdAt: new Date(addDays(hoy, -1).getTime() + 19 * 60 * 60 * 1000).toISOString(),
  },

  // -2 días
  {
    id: 'r-d4',
    canchaId: 'c1',
    canchaNombre: 'Cancha 1 - F5',
    fecha: formatDate(addDays(hoy, -2)),
    horaInicio: '08:00',
    horaFin: '09:00',
    duracionHoras: 1,
    precioTotal: 70,
    precioBase: 80,
    descuentoPromo: 10,
    promocionNombre: 'Mañana activa',
    adelantoPagado: 70,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'efectivo',
    origen: 'manual',
    clienteNombre: 'Pablo Ruiz',
    createdAt: new Date(addDays(hoy, -2).getTime() + 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d5',
    canchaId: 'c2',
    canchaNombre: 'Cancha 2 - F5',
    fecha: formatDate(addDays(hoy, -2)),
    horaInicio: '14:00',
    horaFin: '15:00',
    duracionHoras: 1,
    precioTotal: 90,
    precioBase: 90,
    adelantoPagado: 90,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'yape',
    origen: 'manual',
    extrasTotal: 30,
    clienteNombre: 'Sofia Ramírez',
    createdAt: new Date(addDays(hoy, -2).getTime() + 14 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d6',
    canchaId: 'c3',
    canchaNombre: 'Cancha 3 - F7',
    fecha: formatDate(addDays(hoy, -2)),
    horaInicio: '20:00',
    horaFin: '22:00',
    duracionHoras: 2,
    precioTotal: 400,
    precioBase: 400,
    adelantoPagado: 60,
    saldoPendiente: 340,
    estadoPago: 'partial',
    metodoPago: 'culqi',
    origen: 'app',
    clienteNombre: 'Diego Herrera',
    createdAt: new Date(addDays(hoy, -2).getTime() + 20 * 60 * 60 * 1000).toISOString(),
  },

  // -3 días
  {
    id: 'r-d7',
    canchaId: 'c1',
    canchaNombre: 'Cancha 1 - F5',
    fecha: formatDate(addDays(hoy, -3)),
    horaInicio: '10:00',
    horaFin: '11:00',
    duracionHoras: 1,
    precioTotal: 90,
    precioBase: 90,
    adelantoPagado: 90,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'efectivo',
    origen: 'manual',
    clienteNombre: 'Elena Castro',
    createdAt: new Date(addDays(hoy, -3).getTime() + 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d8',
    canchaId: 'c2',
    canchaNombre: 'Cancha 2 - F5',
    fecha: formatDate(addDays(hoy, -3)),
    horaInicio: '16:00',
    horaFin: '17:00',
    duracionHoras: 1,
    precioTotal: 110,
    precioBase: 110,
    adelantoPagado: 110,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'tarjeta_local',
    origen: 'manual',
    extrasTotal: 48,
    clienteNombre: 'Fernando López',
    createdAt: new Date(addDays(hoy, -3).getTime() + 16 * 60 * 60 * 1000).toISOString(),
  },

  // -4 días
  {
    id: 'r-d9',
    canchaId: 'c3',
    canchaNombre: 'Cancha 3 - F7',
    fecha: formatDate(addDays(hoy, -4)),
    horaInicio: '18:00',
    horaFin: '20:00',
    duracionHoras: 2,
    precioTotal: 350,
    precioBase: 350,
    adelantoPagado: 350,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'plin',
    origen: 'app',
    extrasTotal: 100,
    clienteNombre: 'Carmen Vargas',
    createdAt: new Date(addDays(hoy, -4).getTime() + 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d10',
    canchaId: 'c1',
    canchaNombre: 'Cancha 1 - F5',
    fecha: formatDate(addDays(hoy, -4)),
    horaInicio: '06:00',
    horaFin: '07:00',
    duracionHoras: 1,
    precioTotal: 60,
    precioBase: 60,
    adelantoPagado: 60,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'efectivo',
    origen: 'manual',
    clienteNombre: 'Hugo Medina',
    createdAt: new Date(addDays(hoy, -4).getTime() + 6 * 60 * 60 * 1000).toISOString(),
  },

  // -5 días
  {
    id: 'r-d11',
    canchaId: 'c2',
    canchaNombre: 'Cancha 2 - F5',
    fecha: formatDate(addDays(hoy, -5)),
    horaInicio: '19:00',
    horaFin: '21:00',
    duracionHoras: 2,
    precioTotal: 240,
    precioBase: 240,
    adelantoPagado: 240,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'yape',
    origen: 'manual',
    extrasTotal: 72,
    clienteNombre: 'Lucía Flores',
    createdAt: new Date(addDays(hoy, -5).getTime() + 19 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d12',
    canchaId: 'c3',
    canchaNombre: 'Cancha 3 - F7',
    fecha: formatDate(addDays(hoy, -5)),
    horaInicio: '14:00',
    horaFin: '15:00',
    duracionHoras: 1,
    precioTotal: 140,
    precioBase: 140,
    adelantoPagado: 140,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'efectivo',
    origen: 'manual',
    clienteNombre: 'Alberto Sánchez',
    createdAt: new Date(addDays(hoy, -5).getTime() + 14 * 60 * 60 * 1000).toISOString(),
  },

  // -6 días (completa la semana)
  {
    id: 'r-d13',
    canchaId: 'c1',
    canchaNombre: 'Cancha 1 - F5',
    fecha: formatDate(addDays(hoy, -6)),
    horaInicio: '07:00',
    horaFin: '08:00',
    duracionHoras: 1,
    precioTotal: 80,
    precioBase: 80,
    adelantoPagado: 80,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'efectivo',
    origen: 'manual',
    clienteNombre: 'Patricia Ortega',
    createdAt: new Date(addDays(hoy, -6).getTime() + 7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d14',
    canchaId: 'c2',
    canchaNombre: 'Cancha 2 - F5',
    fecha: formatDate(addDays(hoy, -6)),
    horaInicio: '15:00',
    horaFin: '16:00',
    duracionHoras: 1,
    precioTotal: 100,
    precioBase: 100,
    adelantoPagado: 100,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'tarjeta_local',
    origen: 'manual',
    extrasTotal: 56,
    clienteNombre: 'Raúl Martínez',
    createdAt: new Date(addDays(hoy, -6).getTime() + 15 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r-d15',
    canchaId: 'c3',
    canchaNombre: 'Cancha 3 - F7',
    fecha: formatDate(addDays(hoy, -6)),
    horaInicio: '21:00',
    horaFin: '23:00',
    duracionHoras: 2,
    precioTotal: 380,
    precioBase: 380,
    adelantoPagado: 380,
    saldoPendiente: 0,
    estadoPago: 'completed',
    metodoPago: 'culqi',
    origen: 'app',
    clienteNombre: 'Verónica Nuñez',
    createdAt: new Date(addDays(hoy, -6).getTime() + 21 * 60 * 60 * 1000).toISOString(),
  },
]

// ===========================================
// VENTAS EXTRAS
// ===========================================
export const mockVentasExtras: VentaExtraReporte[] = [
  // Hoy
  {
    id: 've-h1',
    reservaId: 'r-h3',
    productoId: 'p1',
    productoNombre: 'Gaseosa',
    categoria: 'bebida',
    cantidad: 6,
    precioUnitario: 4,
    costoUnitario: 2,
    subtotal: 24,
    metodoPago: 'tarjeta_local',
    fecha: formatDate(hoy),
    clienteNombre: 'Carlos García',
  },
  {
    id: 've-h2',
    reservaId: 'r-h4',
    productoId: 'p2',
    productoNombre: 'Cerveza',
    categoria: 'bebida',
    cantidad: 8,
    precioUnitario: 8,
    costoUnitario: 5,
    subtotal: 64,
    metodoPago: 'yape',
    fecha: formatDate(hoy),
    clienteNombre: 'Pedro Ramos',
  },
  {
    id: 've-h3',
    productoId: 'p3',
    productoNombre: 'Agua mineral',
    categoria: 'bebida',
    cantidad: 3,
    precioUnitario: 3,
    costoUnitario: 1.5,
    subtotal: 9,
    metodoPago: 'efectivo',
    fecha: formatDate(hoy),
    clienteNombre: 'Walk-in cliente',
  },
  {
    id: 've-h4',
    reservaId: 'r-h4',
    productoId: 'p4',
    productoNombre: 'Alquiler balón',
    categoria: 'alquiler',
    cantidad: 1,
    precioUnitario: 10,
    subtotal: 10,
    metodoPago: 'yape',
    fecha: formatDate(hoy),
    clienteNombre: 'Pedro Ramos',
  },

  // -1 día
  {
    id: 've-d1',
    reservaId: 'r-d2',
    productoId: 'p1',
    productoNombre: 'Gaseosa',
    categoria: 'bebida',
    cantidad: 6,
    precioUnitario: 4,
    costoUnitario: 2,
    subtotal: 24,
    metodoPago: 'plin',
    fecha: formatDate(addDays(hoy, -1)),
    clienteNombre: 'Ana Torres',
  },
  {
    id: 've-d2',
    productoId: 'p5',
    productoNombre: 'Papas fritas',
    categoria: 'snack',
    cantidad: 4,
    precioUnitario: 5,
    costoUnitario: 3,
    subtotal: 20,
    metodoPago: 'efectivo',
    fecha: formatDate(addDays(hoy, -1)),
  },

  // -2 días
  {
    id: 've-d3',
    reservaId: 'r-d5',
    productoId: 'p2',
    productoNombre: 'Cerveza',
    categoria: 'bebida',
    cantidad: 4,
    precioUnitario: 8,
    costoUnitario: 5,
    subtotal: 32,
    metodoPago: 'yape',
    fecha: formatDate(addDays(hoy, -2)),
    clienteNombre: 'Sofia Ramírez',
  },
  {
    id: 've-d4',
    productoId: 'p6',
    productoNombre: 'Árbitro',
    categoria: 'servicio',
    cantidad: 1,
    precioUnitario: 50,
    costoUnitario: 40,
    subtotal: 50,
    metodoPago: 'efectivo',
    fecha: formatDate(addDays(hoy, -2)),
  },

  // -3 días
  {
    id: 've-d5',
    reservaId: 'r-d8',
    productoId: 'p3',
    productoNombre: 'Agua mineral',
    categoria: 'bebida',
    cantidad: 12,
    precioUnitario: 3,
    costoUnitario: 1.5,
    subtotal: 36,
    metodoPago: 'tarjeta_local',
    fecha: formatDate(addDays(hoy, -3)),
    clienteNombre: 'Fernando López',
  },
  {
    id: 've-d6',
    productoId: 'p1',
    productoNombre: 'Gaseosa',
    categoria: 'bebida',
    cantidad: 8,
    precioUnitario: 4,
    costoUnitario: 2,
    subtotal: 32,
    metodoPago: 'efectivo',
    fecha: formatDate(addDays(hoy, -3)),
  },

  // -4 días
  {
    id: 've-d7',
    reservaId: 'r-d9',
    productoId: 'p2',
    productoNombre: 'Cerveza',
    categoria: 'bebida',
    cantidad: 10,
    precioUnitario: 8,
    costoUnitario: 5,
    subtotal: 80,
    metodoPago: 'plin',
    fecha: formatDate(addDays(hoy, -4)),
    clienteNombre: 'Carmen Vargas',
  },
  {
    id: 've-d8',
    productoId: 'p7',
    productoNombre: 'Camiseta',
    categoria: 'deportivo',
    cantidad: 2,
    precioUnitario: 15,
    costoUnitario: 8,
    subtotal: 30,
    metodoPago: 'efectivo',
    fecha: formatDate(addDays(hoy, -4)),
  },

  // -5 días
  {
    id: 've-d9',
    reservaId: 'r-d11',
    productoId: 'p1',
    productoNombre: 'Gaseosa',
    categoria: 'bebida',
    cantidad: 6,
    precioUnitario: 4,
    costoUnitario: 2,
    subtotal: 24,
    metodoPago: 'yape',
    fecha: formatDate(addDays(hoy, -5)),
    clienteNombre: 'Lucía Flores',
  },
  {
    id: 've-d10',
    productoId: 'p4',
    productoNombre: 'Alquiler balón',
    categoria: 'alquiler',
    cantidad: 2,
    precioUnitario: 10,
    subtotal: 20,
    metodoPago: 'efectivo',
    fecha: formatDate(addDays(hoy, -5)),
  },

  // -6 días
  {
    id: 've-d11',
    reservaId: 'r-d14',
    productoId: 'p3',
    productoNombre: 'Agua mineral',
    categoria: 'bebida',
    cantidad: 8,
    precioUnitario: 3,
    costoUnitario: 1.5,
    subtotal: 24,
    metodoPago: 'tarjeta_local',
    fecha: formatDate(addDays(hoy, -6)),
    clienteNombre: 'Raúl Martínez',
  },
  {
    id: 've-d12',
    productoId: 'p5',
    productoNombre: 'Papas fritas',
    categoria: 'snack',
    cantidad: 6,
    precioUnitario: 5,
    costoUnitario: 3,
    subtotal: 30,
    metodoPago: 'efectivo',
    fecha: formatDate(addDays(hoy, -6)),
  },
]

// ===========================================
// TENDENCIA MENSUAL (últimos 6 meses)
// ===========================================
export const mockTendenciaMensual: TendenciaMensual[] = [
  {
    mes: '2024-09',
    mesNombre: 'Septiembre',
    ingresosReservas: 8500,
    ingresosExtras: 1200,
    totalIngresos: 9700,
    comparativaAnterior: 8,
  },
  {
    mes: '2024-10',
    mesNombre: 'Octubre',
    ingresosReservas: 9200,
    ingresosExtras: 1450,
    totalIngresos: 10650,
    comparativaAnterior: 10,
  },
  {
    mes: '2024-11',
    mesNombre: 'Noviembre',
    ingresosReservas: 10500,
    ingresosExtras: 1800,
    totalIngresos: 12300,
    comparativaAnterior: 15,
  },
  {
    mes: '2024-12',
    mesNombre: 'Diciembre',
    ingresosReservas: 11200,
    ingresosExtras: 2100,
    totalIngresos: 13300,
    comparativaAnterior: 8,
  },
  {
    mes: '2025-01',
    mesNombre: 'Enero',
    ingresosReservas: 9800,
    ingresosExtras: 1650,
    totalIngresos: 11450,
    comparativaAnterior: -14, // Decrease after holidays
  },
  {
    mes: '2025-02',
    mesNombre: 'Febrero',
    ingresosReservas: 10200,
    ingresosExtras: 1900,
    totalIngresos: 12100,
    comparativaAnterior: 6,
  },
]

// ===========================================
// STATS RESUMEN (calculados pero mock para referencia)
// ===========================================
export const mockIngresosStats: IngresosStats = {
  ingresosTotales: 12100,
  ingresosReservas: 10200,
  ingresosExtras: 1900,
  ingresosPromociones: 40,
  comparativaPorcentaje: 12,
  comparativaReservas: 8,
  comparativaExtras: 15,
  totalReservas: 186,
  reservasCompletadas: 165,
  reservasCanceladas: 5,
  reservasPartial: 16,
  totalVentasExtras: 45,
  ticketPromedioReserva: 54.7,
  ticketPromedioExtra: 42.22,
  saldoPendienteTotal: 530,
  ratioReservasExtras: 84.3, // 10200/12100
  canchaTopNombre: 'Cancha 3 - F7',
  canchaTopIngresos: 4200,
  horarioPeak: '18:00 - 20:00',
  horarioPeakIngresos: 2800,
}
