import type {
  Cancha,
  HorarioDia,
  PrecioSlot,
  BloqueoHorario,
  PlantillaHorario,
  CanchasStats,
} from './types'

// ===========================================
// CANCHAS MOCK
// ===========================================
export const mockCanchas: Cancha[] = [
  {
    id: '1',
    nombre: 'Cancha 1 - Los Campeones',
    direccion: 'Av. Los Deportes 123',
    ciudad: 'Huancayo',
    distrito: 'El Tambo',
    descripcion:
      'Cancha principal con iluminación LED y grass sintético de alta calidad. Ideal para torneos.',
    tipoDeporte: 'f5',
    superficie: 'grass_sintetico',
    capacidad: 10,
    servicios: ['estacionamiento', 'banos', 'duchas', 'iluminacion', 'camerinos'],
    fotos: [],
    estado: 'activa',
    precioHoraBase: 80,
    precioHoraNoche: 120,
    horaInicioDiurno: '06:00',
    horaInicioNoche: '18:00',
    horaCierre: '23:00',
    diasDescanso: [],
    toleranciaMinutos: 15,
    politicaExceso: 'tiempo_restante',
    adelantoMinimo: 30,
    cancelacionHoras: 3,
    reembolsoPorcentaje: 80,
    totalReservas: 45,
    ingresosMes: 3200,
    ocupacionPromedio: 72,
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2026-03-20T15:30:00Z',
  },
  {
    id: '2',
    nombre: 'Cancha 2 - La Gloria',
    direccion: 'Av. Los Deportes 123',
    ciudad: 'Huancayo',
    distrito: 'El Tambo',
    descripcion: 'Cancha mediana con quincho incluido. Perfecta para celebraciones.',
    tipoDeporte: 'f7',
    superficie: 'grass_sintetico',
    capacidad: 14,
    servicios: ['estacionamiento', 'banos', 'quincho', 'iluminacion'],
    fotos: [],
    estado: 'activa',
    precioHoraBase: 100,
    precioHoraNoche: 150,
    horaInicioDiurno: '06:00',
    horaInicioNoche: '18:00',
    horaCierre: '23:00',
    diasDescanso: [],
    toleranciaMinutos: 10,
    politicaExceso: 'penalidad',
    penalidadMonto: 20,
    adelantoMinimo: 40,
    cancelacionHoras: 3,
    reembolsoPorcentaje: 70,
    totalReservas: 38,
    ingresosMes: 2800,
    ocupacionPromedio: 65,
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2026-03-18T12:00:00Z',
  },
  {
    id: '3',
    nombre: 'Cancha 3 - El Triunfo',
    direccion: 'Av. Los Deportes 123',
    ciudad: 'Huancayo',
    distrito: 'El Tambo',
    descripcion: 'Cancha económica de losa. Ideal para partidos informales.',
    tipoDeporte: 'f5',
    superficie: 'losa',
    capacidad: 10,
    servicios: ['banos', 'iluminacion'],
    fotos: [],
    estado: 'activa',
    precioHoraBase: 60,
    precioHoraNoche: 90,
    horaInicioDiurno: '07:00',
    horaInicioNoche: '18:00',
    horaCierre: '21:00',
    diasDescanso: [0], // Descansa domingos
    toleranciaMinutos: 15,
    politicaExceso: 'perder_reserva',
    adelantoMinimo: 25,
    cancelacionHoras: 2,
    reembolsoPorcentaje: 50,
    totalReservas: 28,
    ingresosMes: 1500,
    ocupacionPromedio: 48,
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2026-03-15T09:00:00Z',
  },
  {
    id: '4',
    nombre: 'Cancha 4 - La Cancha Grande',
    direccion: 'Jr. Fútbol 456',
    ciudad: 'Huancayo',
    distrito: 'Chilca',
    descripcion: 'Cancha grande para fútbol 7 con tribuna para espectadores.',
    tipoDeporte: 'f7',
    superficie: 'grass_sintetico',
    capacidad: 14,
    servicios: ['estacionamiento', 'banos', 'duchas', 'iluminacion', 'tribuna', 'cantina'],
    fotos: [],
    estado: 'inactiva',
    precioHoraBase: 120,
    precioHoraNoche: 180,
    horaInicioDiurno: '06:00',
    horaInicioNoche: '18:00',
    horaCierre: '22:00',
    diasDescanso: [],
    toleranciaMinutos: 15,
    politicaExceso: 'configurable',
    adelantoMinimo: 50,
    cancelacionHoras: 4,
    reembolsoPorcentaje: 90,
    totalReservas: 0,
    ingresosMes: 0,
    ocupacionPromedio: 0,
    createdAt: '2025-03-01T10:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
]

// ===========================================
// HORARIOS POR DÍA (para cada cancha)
// ===========================================
export const mockHorarios: HorarioDia[] = [
  // Cancha 1
  {
    id: 'h1-0',
    canchaId: '1',
    diaSemana: 0,
    horaApertura: '08:00',
    horaCierre: '20:00',
    activo: true,
  },
  {
    id: 'h1-1',
    canchaId: '1',
    diaSemana: 1,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h1-2',
    canchaId: '1',
    diaSemana: 2,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h1-3',
    canchaId: '1',
    diaSemana: 3,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h1-4',
    canchaId: '1',
    diaSemana: 4,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h1-5',
    canchaId: '1',
    diaSemana: 5,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h1-6',
    canchaId: '1',
    diaSemana: 6,
    horaApertura: '06:00',
    horaCierre: '22:00',
    activo: true,
  },
  // Cancha 2
  {
    id: 'h2-0',
    canchaId: '2',
    diaSemana: 0,
    horaApertura: '08:00',
    horaCierre: '20:00',
    activo: true,
  },
  {
    id: 'h2-1',
    canchaId: '2',
    diaSemana: 1,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h2-2',
    canchaId: '2',
    diaSemana: 2,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h2-3',
    canchaId: '2',
    diaSemana: 3,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h2-4',
    canchaId: '2',
    diaSemana: 4,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h2-5',
    canchaId: '2',
    diaSemana: 5,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  {
    id: 'h2-6',
    canchaId: '2',
    diaSemana: 6,
    horaApertura: '06:00',
    horaCierre: '23:00',
    activo: true,
  },
  // Cancha 3
  {
    id: 'h3-0',
    canchaId: '3',
    diaSemana: 0,
    horaApertura: '07:00',
    horaCierre: '21:00',
    activo: false,
  }, // Descansa domingo
  {
    id: 'h3-1',
    canchaId: '3',
    diaSemana: 1,
    horaApertura: '07:00',
    horaCierre: '21:00',
    activo: true,
  },
  {
    id: 'h3-2',
    canchaId: '3',
    diaSemana: 2,
    horaApertura: '07:00',
    horaCierre: '21:00',
    activo: true,
  },
  {
    id: 'h3-3',
    canchaId: '3',
    diaSemana: 3,
    horaApertura: '07:00',
    horaCierre: '21:00',
    activo: true,
  },
  {
    id: 'h3-4',
    canchaId: '3',
    diaSemana: 4,
    horaApertura: '07:00',
    horaCierre: '21:00',
    activo: true,
  },
  {
    id: 'h3-5',
    canchaId: '3',
    diaSemana: 5,
    horaApertura: '07:00',
    horaCierre: '21:00',
    activo: true,
  },
  {
    id: 'h3-6',
    canchaId: '3',
    diaSemana: 6,
    horaApertura: '07:00',
    horaCierre: '21:00',
    activo: true,
  },
]

// ===========================================
// PRECIOS POR SLOT
// ===========================================
export const mockPreciosSlots: PrecioSlot[] = [
  // Cancha 1 - Lunes (ejemplo)
  { id: 'ps1-1', canchaId: '1', diaSemana: 1, horaInicio: '06:00', precio: 60, esPremium: false },
  { id: 'ps1-2', canchaId: '1', diaSemana: 1, horaInicio: '07:00', precio: 60, esPremium: false },
  { id: 'ps1-3', canchaId: '1', diaSemana: 1, horaInicio: '08:00', precio: 80, esPremium: false },
  { id: 'ps1-4', canchaId: '1', diaSemana: 1, horaInicio: '09:00', precio: 80, esPremium: false },
  { id: 'ps1-5', canchaId: '1', diaSemana: 1, horaInicio: '10:00', precio: 80, esPremium: false },
  { id: 'ps1-6', canchaId: '1', diaSemana: 1, horaInicio: '15:00', precio: 100, esPremium: true },
  { id: 'ps1-7', canchaId: '1', diaSemana: 1, horaInicio: '16:00', precio: 100, esPremium: true },
  { id: 'ps1-8', canchaId: '1', diaSemana: 1, horaInicio: '17:00', precio: 90, esPremium: false },
  { id: 'ps1-9', canchaId: '1', diaSemana: 1, horaInicio: '18:00', precio: 120, esPremium: true },
  { id: 'ps1-10', canchaId: '1', diaSemana: 1, horaInicio: '19:00', precio: 120, esPremium: true },
  { id: 'ps1-11', canchaId: '1', diaSemana: 1, horaInicio: '20:00', precio: 120, esPremium: true },
]

// ===========================================
// BLOQUEOS DE HORARIO
// ===========================================
function getDate(daysFromToday: number): string {
  const date = new Date()
  date.setDate(date.getDate() + daysFromToday)
  return date.toISOString().split('T')[0]
}

export const mockBloqueos: BloqueoHorario[] = [
  {
    id: 'b1',
    canchaId: '1',
    canchaNombre: 'Cancha 1 - Los Campeones',
    fecha: getDate(3),
    horaInicio: '12:00',
    horaFin: '14:00',
    motivo: 'Mantenimiento del césped sintético',
    esRecurrente: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b2',
    canchaId: '2',
    canchaNombre: 'Cancha 2 - La Gloria',
    fecha: getDate(5),
    horaInicio: '08:00',
    horaFin: '10:00',
    motivo: 'Evento privado - Cumpleaños',
    esRecurrente: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b3',
    canchaId: '1',
    canchaNombre: 'Cancha 1 - Los Campeones',
    fecha: getDate(7),
    horaInicio: '06:00',
    horaFin: '08:00',
    motivo: 'Limpieza semanal',
    esRecurrente: true,
    diasRecurrencia: [1], // Todos los lunes
    createdAt: new Date().toISOString(),
  },
]

// ===========================================
// PLANTILLAS DE HORARIOS
// ===========================================
export const mockPlantillas: PlantillaHorario[] = [
  {
    id: 'p1',
    nombre: 'Horario Normal',
    descripcion: 'Precios estándar para días laborables',
    precios: [
      { horaInicio: '06:00', precio: 60, esPremium: false },
      { horaInicio: '07:00', precio: 60, esPremium: false },
      { horaInicio: '08:00', precio: 80, esPremium: false },
      { horaInicio: '09:00', precio: 80, esPremium: false },
      { horaInicio: '10:00', precio: 80, esPremium: false },
      { horaInicio: '11:00', precio: 80, esPremium: false },
      { horaInicio: '12:00', precio: 80, esPremium: false },
      { horaInicio: '13:00', precio: 80, esPremium: false },
      { horaInicio: '14:00', precio: 80, esPremium: false },
      { horaInicio: '15:00', precio: 100, esPremium: true },
      { horaInicio: '16:00', precio: 100, esPremium: true },
      { horaInicio: '17:00', precio: 90, esPremium: false },
      { horaInicio: '18:00', precio: 120, esPremium: true },
      { horaInicio: '19:00', precio: 120, esPremium: true },
      { horaInicio: '20:00', precio: 120, esPremium: true },
      { horaInicio: '21:00', precio: 110, esPremium: false },
      { horaInicio: '22:00', precio: 100, esPremium: false },
    ],
  },
  {
    id: 'p2',
    nombre: 'Fin de Semana',
    descripcion: 'Precios especiales para sábados y domingos',
    precios: [
      { horaInicio: '06:00', precio: 80, esPremium: false },
      { horaInicio: '07:00', precio: 80, esPremium: false },
      { horaInicio: '08:00', precio: 100, esPremium: false },
      { horaInicio: '09:00', precio: 100, esPremium: false },
      { horaInicio: '10:00', precio: 120, esPremium: true },
      { horaInicio: '11:00', precio: 120, esPremium: true },
      { horaInicio: '12:00', precio: 120, esPremium: true },
      { horaInicio: '13:00', precio: 120, esPremium: true },
      { horaInicio: '14:00', precio: 120, esPremium: true },
      { horaInicio: '15:00', precio: 140, esPremium: true },
      { horaInicio: '16:00', precio: 140, esPremium: true },
      { horaInicio: '17:00', precio: 130, esPremium: false },
      { horaInicio: '18:00', precio: 150, esPremium: true },
      { horaInicio: '19:00', precio: 150, esPremium: true },
      { horaInicio: '20:00', precio: 150, esPremium: true },
      { horaInicio: '21:00', precio: 140, esPremium: false },
    ],
  },
]

// ===========================================
// ESTADÍSTICAS
// ===========================================
export const mockCanchasStats: CanchasStats = {
  total: 4,
  activas: 3,
  inactivas: 1,
  reservasHoy: 8,
  ingresosMes: 7500,
  ocupacionPromedio: 62,
}
