import type { Promocion, UsoPromocion, SugerenciaBajaDemanda, PromocionesStats } from './types'

// ===========================================
// PROMOCIONES MOCK
// ===========================================
export const mockPromociones: Promocion[] = [
  {
    id: '1',
    nombre: 'Martes de Mañana',
    descripcion: 'Disfruta un 20% de descuento en todos los horarios de la mañana los martes.',
    tipo: 'descuento_porcentual',
    valor: 20,
    canchasAplicables: ['1', '2', '3'],
    diasAplicables: [2],
    horarios: [{ inicio: '06:00', fin: '12:00' }],
    fechaInicio: '2026-03-01',
    fechaFin: '2026-04-30',
    cuposMaximos: 10,
    cuposPorUsuario: 3,
    anticipacionMinima: 0,
    combinable: false,
    estado: 'activa',
    activa: true,
    usosTotales: 47,
    usosSemana: 8,
    cuposUsadosHoy: 3,
    ahorroGenerado: 850,
    ingresosGenerados: 3400,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-20T15:00:00Z',
  },
  {
    id: '2',
    nombre: 'Miércoles 2x1.5 Horas',
    descripcion: 'Reserva 2 horas y solo paga 1.5. Perfecto para partidos más largos.',
    tipo: 'combo_horas',
    valor: 25,
    horasBase: 2,
    horasCobradas: 1.5,
    canchasAplicables: ['1', '2'],
    diasAplicables: [3],
    horarios: [{ inicio: '06:00', fin: '23:00' }],
    fechaInicio: '2026-03-01',
    fechaFin: '2026-03-31',
    cuposMaximos: 5,
    cuposPorUsuario: 2,
    anticipacionMinima: 1,
    combinable: false,
    estado: 'agotada',
    activa: true,
    usosTotales: 23,
    usosSemana: 5,
    cuposUsadosHoy: 5,
    ahorroGenerado: 690,
    ingresosGenerados: 2070,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-18T12:00:00Z',
  },
  {
    id: '3',
    nombre: 'Noche de Jueves',
    descripcion: 'Precio especial de S/60 por hora en horario nocturno.',
    tipo: 'precio_fijo',
    valor: 60,
    canchasAplicables: ['1'],
    diasAplicables: [4],
    horarios: [{ inicio: '20:00', fin: '23:00' }],
    fechaInicio: '2026-03-15',
    fechaFin: '2026-05-15',
    cuposMaximos: 8,
    cuposPorUsuario: 4,
    anticipacionMinima: 0,
    combinable: true,
    estado: 'activa',
    activa: false,
    usosTotales: 12,
    usosSemana: 2,
    cuposUsadosHoy: 0,
    ahorroGenerado: 240,
    ingresosGenerados: 720,
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-03-15T10:00:00Z',
  },
  {
    id: '4',
    nombre: 'Pack Fútbol + Bebidas',
    descripcion: 'Reserva tu cancha y llévate 6 gaseosas incluidas.',
    tipo: 'combo_productos',
    valor: 120,
    productosIncluidos: [{ productoId: 'p1', productoNombre: 'Gaseosa 500ml', cantidad: 6 }],
    canchasAplicables: ['1', '2'],
    diasAplicables: [5, 6],
    horarios: [{ inicio: '18:00', fin: '23:00' }],
    fechaInicio: '2026-03-01',
    fechaFin: '2026-04-30',
    cuposMaximos: 6,
    cuposPorUsuario: 2,
    anticipacionMinima: 2,
    combinable: false,
    estado: 'activa',
    activa: true,
    usosTotales: 18,
    usosSemana: 4,
    cuposUsadosHoy: 1,
    ahorroGenerado: 270,
    ingresosGenerados: 2160,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-19T18:00:00Z',
  },
  {
    id: '5',
    nombre: 'Cliente Frecuente',
    descripcion: 'En tu tercera reserva del mes, obtén 15% de descuento.',
    tipo: 'recurrencia',
    valor: 15,
    numeroReserva: 3,
    canchasAplicables: ['1', '2', '3'],
    diasAplicables: [0, 1, 2, 3, 4, 5, 6],
    horarios: [{ inicio: '06:00', fin: '23:00' }],
    fechaInicio: '2026-01-01',
    fechaFin: '2026-12-31',
    cuposMaximos: 999,
    cuposPorUsuario: 999,
    anticipacionMinima: 0,
    combinable: false,
    estado: 'activa',
    activa: true,
    usosTotales: 89,
    usosSemana: 15,
    cuposUsadosHoy: 0,
    ahorroGenerado: 1780,
    ingresosGenerados: 10120,
    createdAt: '2026-01-01T10:00:00Z',
    updatedAt: '2026-03-20T09:00:00Z',
  },
  {
    id: '6',
    nombre: 'Happy Hour Lunes',
    descripcion: 'Promoción vencida.',
    tipo: 'descuento_porcentual',
    valor: 30,
    canchasAplicables: ['1'],
    diasAplicables: [1],
    horarios: [{ inicio: '14:00', fin: '18:00' }],
    fechaInicio: '2026-02-01',
    fechaFin: '2026-02-28',
    cuposMaximos: 5,
    cuposPorUsuario: 1,
    anticipacionMinima: 0,
    combinable: true,
    estado: 'vencida',
    activa: false,
    usosTotales: 15,
    usosSemana: 0,
    cuposUsadosHoy: 0,
    ahorroGenerado: 360,
    ingresosGenerados: 840,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
  },
]

// ===========================================
// USOS DE PROMOCIONES
// ===========================================
export const mockUsos: UsoPromocion[] = [
  {
    id: 'u1',
    promocionId: '1',
    promocionNombre: 'Martes de Mañana',
    reservaId: 'r1',
    clienteNombre: 'Carlos Mendoza',
    clienteTelefono: '999888777',
    canchaNombre: 'Cancha 1 - Los Campeones',
    fecha: '2026-03-25',
    hora: '08:00',
    precioOriginal: 160,
    descuentoAplicado: 32,
    precioFinal: 128,
    createdAt: '2026-03-25T08:00:00Z',
  },
  {
    id: 'u2',
    promocionId: '1',
    promocionNombre: 'Martes de Mañana',
    reservaId: 'r2',
    clienteNombre: 'Ana García',
    clienteTelefono: '997654321',
    canchaNombre: 'Cancha 2 - La Gloria',
    fecha: '2026-03-25',
    hora: '09:00',
    precioOriginal: 200,
    descuentoAplicado: 40,
    precioFinal: 160,
    createdAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'u3',
    promocionId: '2',
    promocionNombre: 'Miércoles 2x1.5 Horas',
    reservaId: 'r3',
    clienteNombre: 'Miguel Torres',
    clienteTelefono: '998765432',
    canchaNombre: 'Cancha 1 - Los Campeones',
    fecha: '2026-03-26',
    hora: '15:00',
    precioOriginal: 200,
    descuentoAplicado: 50,
    precioFinal: 150,
    createdAt: '2026-03-26T15:00:00Z',
  },
]

// ===========================================
// SUGERENCIAS DE BAJA DEMANDA
// ===========================================
export const mockSugerencias: SugerenciaBajaDemanda[] = [
  {
    id: 's1',
    canchaId: '3',
    canchaNombre: 'Cancha 3 - El Triunfo',
    diaSemana: 1,
    diaNombre: 'Lunes',
    horaInicio: '06:00',
    horaFin: '10:00',
    ocupacionActual: 8,
    reservasActuales: 0,
    promocionSugerida: {
      tipo: 'descuento_porcentual',
      valor: 30,
      nombre: 'Lunes Temprano - 30% OFF',
    },
    descartada: false,
  },
  {
    id: 's2',
    canchaId: '1',
    canchaNombre: 'Cancha 1 - Los Campeones',
    diaSemana: 3,
    diaNombre: 'Miércoles',
    horaInicio: '12:00',
    horaFin: '15:00',
    ocupacionActual: 12,
    reservasActuales: 1,
    promocionSugerida: { tipo: 'precio_fijo', valor: 60, nombre: 'Mediodía Miércoles - S/60' },
    descartada: false,
  },
  {
    id: 's3',
    canchaId: '2',
    canchaNombre: 'Cancha 2 - La Gloria',
    diaSemana: 0,
    diaNombre: 'Domingo',
    horaInicio: '06:00',
    horaFin: '09:00',
    ocupacionActual: 0,
    reservasActuales: 0,
    promocionSugerida: {
      tipo: 'descuento_porcentual',
      valor: 40,
      nombre: 'Domingo Madrugada - 40% OFF',
    },
    descartada: false,
  },
]

// ===========================================
// ESTADÍSTICAS
// ===========================================
export const mockPromocionesStats: PromocionesStats = {
  total: 6,
  activas: 4,
  inactivas: 2,
  usosSemana: 34,
  usosMes: 142,
  ahorroClientes: 4190,
  ingresosGenerados: 19310,
}

// ===========================================
// CANCHAS Y PRODUCTOS
// ===========================================
export const mockCanchasPromo = [
  { id: '1', nombre: 'Cancha 1 - Los Campeones' },
  { id: '2', nombre: 'Cancha 2 - La Gloria' },
  { id: '3', nombre: 'Cancha 3 - El Triunfo' },
]

export const mockProductosPromo = [
  { id: 'p1', nombre: 'Gaseosa 500ml', precio: 4 },
  { id: 'p2', nombre: 'Agua mineral', precio: 3 },
  { id: 'p3', nombre: 'Cerveza', precio: 8 },
  { id: 'p4', nombre: 'Papas fritas', precio: 5 },
]
