import type { Producto, Venta, MovimientoInventario, InventarioStats } from './types'

// ===========================================
// PRODUCTOS MOCK
// ===========================================
export const mockProductos: Producto[] = [
  // Bebidas
  {
    id: 'p1',
    nombre: 'Agua mineral',
    descripcion: 'Agua mineral 500ml',
    categoria: 'bebida',
    precio: 3.0,
    costo: 1.2,
    controlStock: true,
    stockActual: 48,
    stockMinimo: 10,
    activo: true,
    totalVendidos: 156,
    ingresosGenerados: 468,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-20T15:00:00Z',
  },
  {
    id: 'p2',
    nombre: 'Gaseosa',
    descripcion: 'Gaseosa 500ml variados sabores',
    categoria: 'bebida',
    precio: 4.0,
    costo: 2.0,
    controlStock: true,
    stockActual: 6,
    stockMinimo: 15,
    activo: true,
    totalVendidos: 89,
    ingresosGenerados: 356,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-21T12:00:00Z',
  },
  {
    id: 'p3',
    nombre: 'Cerveza',
    descripcion: 'Cerveza 650ml',
    categoria: 'bebida',
    precio: 8.0,
    costo: 5.0,
    controlStock: true,
    stockActual: 24,
    stockMinimo: 12,
    activo: true,
    totalVendidos: 67,
    ingresosGenerados: 536,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-19T18:00:00Z',
  },
  {
    id: 'p4',
    nombre: 'Jugo natural',
    descripcion: 'Jugo natural de frutas 400ml',
    categoria: 'bebida',
    precio: 5.0,
    costo: 2.5,
    controlStock: true,
    stockActual: 3,
    stockMinimo: 8,
    activo: true,
    totalVendidos: 45,
    ingresosGenerados: 225,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-22T09:00:00Z',
  },

  // Snacks
  {
    id: 'p5',
    nombre: 'Papas fritas',
    descripcion: 'Papas fritas bolsa 150g',
    categoria: 'snack',
    precio: 5.0,
    costo: 2.5,
    controlStock: true,
    stockActual: 18,
    stockMinimo: 10,
    activo: true,
    totalVendidos: 34,
    ingresosGenerados: 170,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-18T14:00:00Z',
  },
  {
    id: 'p6',
    nombre: 'Maní salado',
    descripcion: 'Maní salado 200g',
    categoria: 'snack',
    precio: 3.0,
    costo: 1.5,
    controlStock: true,
    stockActual: 25,
    stockMinimo: 8,
    activo: true,
    totalVendidos: 28,
    ingresosGenerados: 84,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-20T11:00:00Z',
  },

  // Artículos Deportivos
  {
    id: 'p7',
    nombre: 'Balón de fútbol',
    descripcion: 'Balón de fútbol calidad profesional',
    categoria: 'deportivo',
    precio: 35.0,
    costo: 20.0,
    controlStock: true,
    stockActual: 4,
    stockMinimo: 3,
    activo: true,
    totalVendidos: 8,
    ingresosGenerados: 280,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-03-15T16:00:00Z',
  },

  // Alquiler
  {
    id: 'p8',
    nombre: 'Alquiler de balón',
    descripcion: 'Alquiler de balón por partido',
    categoria: 'alquiler',
    precio: 10.0,
    costo: 0,
    controlStock: false,
    activo: true,
    totalVendidos: 89,
    ingresosGenerados: 890,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-22T17:00:00Z',
  },
  {
    id: 'p9',
    nombre: 'Árbitro',
    descripcion: 'Servicio de árbitro profesional',
    categoria: 'alquiler',
    precio: 50.0,
    costo: 40.0,
    controlStock: false,
    activo: true,
    totalVendidos: 23,
    ingresosGenerados: 1150,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-21T14:00:00Z',
  },
  {
    id: 'p10',
    nombre: 'Camerinos',
    descripcion: 'Alquiler de camerinos con duchas',
    categoria: 'alquiler',
    precio: 15.0,
    costo: 0,
    controlStock: false,
    activo: true,
    totalVendidos: 12,
    ingresosGenerados: 180,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-19T10:00:00Z',
  },

  // Servicios
  {
    id: 'p11',
    nombre: 'Estacionamiento',
    descripcion: 'Tarifa de estacionamiento',
    categoria: 'servicio',
    precio: 5.0,
    costo: 0,
    controlStock: false,
    activo: true,
    totalVendidos: 234,
    ingresosGenerados: 1170,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-22T18:00:00Z',
  },
  {
    id: 'p12',
    nombre: 'Quincho',
    descripcion: 'Alquiler de quincho para eventos',
    categoria: 'servicio',
    precio: 100.0,
    costo: 0,
    controlStock: false,
    activo: true,
    totalVendidos: 5,
    ingresosGenerados: 500,
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-03-17T12:00:00Z',
  },

  // Producto inactivo
  {
    id: 'p13',
    nombre: 'Chocolates',
    descripcion: 'Chocolates variados (descontinuado)',
    categoria: 'snack',
    precio: 4.0,
    costo: 2.0,
    controlStock: true,
    stockActual: 15,
    stockMinimo: 5,
    activo: false,
    totalVendidos: 12,
    ingresosGenerados: 48,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
]

// ===========================================
// VENTAS MOCK
// ===========================================
function getDateString(daysAgo: number): string {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  return date.toISOString().split('T')[0]
}

export const mockVentas: Venta[] = [
  {
    id: 'v1',
    productos: [
      {
        productoId: 'p1',
        productoNombre: 'Agua mineral',
        categoria: 'bebida',
        cantidad: 6,
        precioUnitario: 3,
        subtotal: 18,
      },
      {
        productoId: 'p2',
        productoNombre: 'Gaseosa',
        categoria: 'bebida',
        cantidad: 4,
        precioUnitario: 4,
        subtotal: 16,
      },
    ],
    clienteNombre: 'Carlos Mendoza',
    clienteTelefono: '999888777',
    total: 34,
    metodoPago: 'efectivo',
    fecha: getDateString(0),
    vendedorId: 'u1',
    vendedorNombre: 'Admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'v2',
    productos: [
      {
        productoId: 'p8',
        productoNombre: 'Alquiler de balón',
        categoria: 'alquiler',
        cantidad: 1,
        precioUnitario: 10,
        subtotal: 10,
      },
      {
        productoId: 'p5',
        productoNombre: 'Papas fritas',
        categoria: 'snack',
        cantidad: 2,
        precioUnitario: 5,
        subtotal: 10,
      },
    ],
    clienteNombre: 'Miguel Torres',
    total: 20,
    metodoPago: 'yape',
    fecha: getDateString(0),
    vendedorId: 'u1',
    vendedorNombre: 'Admin',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'v3',
    productos: [
      {
        productoId: 'p9',
        productoNombre: 'Árbitro',
        categoria: 'alquiler',
        cantidad: 1,
        precioUnitario: 50,
        subtotal: 50,
      },
    ],
    reservaId: 'r1',
    reservaInfo: 'Reserva #r1',
    total: 50,
    metodoPago: 'efectivo',
    fecha: getDateString(0),
    vendedorId: 'u1',
    vendedorNombre: 'Admin',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'v4',
    productos: [
      {
        productoId: 'p3',
        productoNombre: 'Cerveza',
        categoria: 'bebida',
        cantidad: 8,
        precioUnitario: 8,
        subtotal: 64,
      },
      {
        productoId: 'p6',
        productoNombre: 'Maní salado',
        categoria: 'snack',
        cantidad: 3,
        precioUnitario: 3,
        subtotal: 9,
      },
    ],
    clienteNombre: 'Pedro López',
    clienteTelefono: '996543210',
    total: 73,
    metodoPago: 'tarjeta',
    fecha: getDateString(1),
    vendedorId: 'u1',
    vendedorNombre: 'Admin',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'v5',
    productos: [
      {
        productoId: 'p11',
        productoNombre: 'Estacionamiento',
        categoria: 'servicio',
        cantidad: 3,
        precioUnitario: 5,
        subtotal: 15,
      },
      {
        productoId: 'p4',
        productoNombre: 'Jugo natural',
        categoria: 'bebida',
        cantidad: 3,
        precioUnitario: 5,
        subtotal: 15,
      },
    ],
    total: 30,
    metodoPago: 'plin',
    fecha: getDateString(1),
    vendedorId: 'u1',
    vendedorNombre: 'Admin',
    createdAt: new Date(Date.now() - 90000000).toISOString(),
  },
  {
    id: 'v6',
    productos: [
      {
        productoId: 'p2',
        productoNombre: 'Gaseosa',
        categoria: 'bebida',
        cantidad: 12,
        precioUnitario: 4,
        subtotal: 48,
      },
    ],
    clienteNombre: 'Ana García',
    clienteTelefono: '997654321',
    total: 48,
    metodoPago: 'efectivo',
    fecha: getDateString(2),
    vendedorId: 'u1',
    vendedorNombre: 'Admin',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
]

// ===========================================
// MOVIMIENTOS DE INVENTARIO MOCK
// ===========================================
export const mockMovimientos: MovimientoInventario[] = [
  {
    id: 'm1',
    productoId: 'p2',
    productoNombre: 'Gaseosa',
    tipo: 'venta',
    cantidad: 4,
    stockAnterior: 10,
    stockNuevo: 6,
    usuarioId: 'u1',
    usuarioNombre: 'Admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'm2',
    productoId: 'p1',
    productoNombre: 'Agua mineral',
    tipo: 'venta',
    cantidad: 6,
    stockAnterior: 54,
    stockNuevo: 48,
    usuarioId: 'u1',
    usuarioNombre: 'Admin',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'm3',
    productoId: 'p3',
    productoNombre: 'Cerveza',
    tipo: 'entrada',
    cantidad: 12,
    stockAnterior: 12,
    stockNuevo: 24,
    observaciones: 'Compra proveedor - Lote #123',
    usuarioId: 'u1',
    usuarioNombre: 'Admin',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'm4',
    productoId: 'p4',
    productoNombre: 'Jugo natural',
    tipo: 'salida',
    cantidad: 2,
    stockAnterior: 5,
    stockNuevo: 3,
    observaciones: 'Producto vencido',
    usuarioId: 'u1',
    usuarioNombre: 'Admin',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'm5',
    productoId: 'p5',
    productoNombre: 'Papas fritas',
    tipo: 'entrada',
    cantidad: 10,
    stockAnterior: 8,
    stockNuevo: 18,
    observaciones: 'Reposición de stock',
    usuarioId: 'u1',
    usuarioNombre: 'Admin',
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
]

// ===========================================
// ESTADÍSTICAS
// ===========================================
export const mockInventarioStats: InventarioStats = {
  totalProductos: 13,
  productosActivos: 12,
  stockBajo: 2,
  ventasHoy: 3,
  ventasSemana: 6,
  ingresosHoy: 104,
  ingresosSemana: 255,
  margenPromedio: 42,
}
